plugins {
    id("org.jetbrains.intellij.platform") version "2.10.2"
    id("java")
    id("idea")
}

group = 'de.junidas.webobjects.ijplugin'
version = '0.7.3'

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

sourceSets {
    main {
        java {
            srcDirs("src/main/gen")
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    // IntelliJ Platform + zusätzliche Plugins
    intellijPlatform {
        create("IC", "2025.2.4")
        bundledPlugin("com.intellij.java")

        // Test Framework (bringt JUnit 4 + IntelliJ‑Test‑Infrastruktur)
        // testFramework()
    }

    // Weitere Dependencies
    implementation("org.jetbrains:annotations:24.0.0")
    implementation("org.apache.commons:commons-lang3:3.18.0")
    implementation("org.seleniumhq.selenium:htmlunit3-driver:4.9.1")

    // JUnit Platform Launcher – nötig für Gradle Test‑Executor
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.2")

    // JUnit 5
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    // JUnit 4 (nur für @Rule‑Schnittstelle, z. B. org.junit.rules.TestRule)
    testImplementation("junit:junit:4.13.2")
}

test {
    // JUnit 5 Test‑Runner aktivieren
    useJUnitPlatform()
}
