{
  parserClass="org.wocommunity.plugins.intellij.wod.parser.WODParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix=""
  psiImplClassSuffix="Impl"
  psiPackage="org.wocommunity.plugins.intellij.wod.psi"
  psiImplPackage="org.wocommunity.plugins.intellij.wod.psi.impl"

  elementTypeHolderClass="org.wocommunity.plugins.intellij.wod.psi.WODTypes"
  elementTypeClass="org.wocommunity.plugins.intellij.wod.psi.WODElementType"
  tokenTypeClass="org.wocommunity.plugins.intellij.wod.psi.WODTokenType"

  tokens = [
    SEMI=';'
    COLON=':'
    ASSIGN='='
    LBRACE='{'
    RBRACE='}'
    DOT='.'
    WS="regexp:\s+"

    IDENTIFIER="regexp:[a-zA-Z_][a-zA-Z0-9_]*"
    NUMBER="regexp:[0-9]+"
    STRING="regexp:\"([^\\\"\r\n]|\\[^\r\n])*\""

    // Support for both line and block comments
    COMMENT="regexp://.*|/\*([^*]|\*+[^*/])*\*+/"
  ]
}

wodFile ::= declaration *

declaration ::= WODElement COLON WODComponent LBRACE assignment_list RBRACE {
    pin=1
}

WODElement ::= IDENTIFIER

WODComponent ::= IDENTIFIER

assignment_list ::= assignment *

assignment ::= WODBinding ASSIGN WODValue SEMI {
    pin=1
}

WODBinding ::= IDENTIFIER

WODValue ::= STRING | WODKeyPath | NUMBER

WODKeyPath ::= IDENTIFIER (DOT IDENTIFIER)*