{
  parserClass="org.wocommunity.plugins.intellij.wod.parser.WODParser"
  parserUtilClass="org.wocommunity.plugins.intellij.wod.parser.WODParserUtil"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix=""
  psiImplClassSuffix="Impl"
  psiPackage="org.wocommunity.plugins.intellij.psi.wod"
  psiImplPackage="org.wocommunity.plugins.intellij.psi.wod.impl"
  generate=[visitor="no"]

  elementTypeHolderClass="org.wocommunity.plugins.intellij.psi.wod.WODTypes"
  elementTypeClass="org.wocommunity.plugins.intellij.psi.wod.WODElementType"
  tokenTypeClass="org.wocommunity.plugins.intellij.psi.wod.WODTokenType"

  tokens = [
    SEMI=';'
    CARET='^'
    COLON=':'
    ASSIGN='='
    LBRACE='{'
    RBRACE='}'
    SLASH='/'
    DOT='.'
    WS="regexp:\s+"
    VALID_KEYWORD='valid'

    IDENTIFIER="regexp:[a-zA-Z_][a-zA-Z0-9_\-]*"
    NUMBER="regexp:[0-9]+"
    STRING="regexp:\"([^\\\"\r\n]|\\[^\r\n])*\""

    // Support for both line and block comments
    COMMENT="regexp://.*|/\*([^*]|\*+[^*/])*\*+/"
  ]
}

WODFile ::= WODDeclaration *

WODDeclaration ::= WODElement COLON WODComponent LBRACE WODAssignmentList RBRACE {
    pin=1
}

WODElement ::= IDENTIFIER {
    mixin="org.wocommunity.plugins.intellij.psi.wod.impl.WODElementMixin"
}

WODComponent ::= IDENTIFIER

WODAssignmentList ::= WODAssignment *

WODAssignment ::= WODBinding ASSIGN WODValue SEMI WODAssignmentComment? {
    pin=1
}

WODAssignmentComment ::= SLASH SLASH VALID_KEYWORD

WODBinding ::= IDENTIFIER

WODValue ::= STRING | WODParentBinding | WODKeyPath | NUMBER

WODParentBinding ::= CARET IDENTIFIER

WODKeyPath ::= WODKeyPathElement (DOT WODKeyPathElement)*

WODKeyPathElement ::= IDENTIFIER {
    mixin="org.wocommunity.plugins.intellij.psi.wod.impl.WODKeyPathElementMixin"
}
